#!/bin/bash

if grep -q 'Raspberry Pi' /proc/device-tree/model; then
    sed -i -e 's/User=respeaker/User=pi/' /lib/systemd/system/respeakerd.service
    sed -i -e 's/Group=respeaker/Group=pi/' /lib/systemd/system/respeakerd.service
fi

if [[ -e /etc/systemd/system/respeakerd.service ]] ; then
    # users may installed the service here according to the previous guide
    rm /etc/systemd/system/respeakerd.service
fi

#DEBHELPER#
