#!/bin/bash

echo "Setting up respeakerd ..."

PLATFORM=pi
if [[ $(grep -c RK3229 /proc/device-tree/model) == 1 ]] ; then
    PLATFORM=axol
fi

echo "The platform is $PLATFORM"

if [[ $PLATFORM == pi ]] ; then
    sed -i -e 's/User=respeaker/User=pi/' /etc/systemd/system/respeakerd.service
    sed -i -e 's/Group=respeaker/Group=pi/' /etc/systemd/system/respeakerd.service
    cp -f /usr/share/respeaker/seeed-voicecard/pulse_config_4mic/seeed-voicecard.conf /usr/share/pulseaudio/alsa-mixer/profile-sets/seeed-voicecard-4mic.conf
    cp -f /usr/share/respeaker/seeed-voicecard/pulse_config_6mic/seeed-voicecard.conf /usr/share/pulseaudio/alsa-mixer/profile-sets/seeed-voicecard-8mic.conf
    cp -f /usr/share/respeaker/seeed-voicecard/91-seeedvoicecard.rules /etc/udev/rules.d/91-seeedvoicecard.rules
fi

echo "Reloading service respeakerd ..."
systemctl daemon-reload
echo "Starting service respeakerd ..."
systemctl enable respeakerd
systemctl start respeakerd

# echo "Installing Python deps for clients ..."
# pip install avs pixel_ring voice-engine pydbus

exit 0
